logging:
  level:
    org.springframework: debug

spring:
  messages:
    basename: messages
  security:
    user:
      name: username
      password: password
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
